/* HistorIA v2.0.2 (full) */
(function(){const DB='historIA_db',VER=1,STORE='stories';let idb;
const $=s=>document.querySelector(s), S={stories:[],current:null,chapterIdx:0};
function openDB(){return new Promise((r,j)=>{const q=indexedDB.open(DB,VER);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}
async function idbGetAll(){idb=idb||await openDB();return new Promise((r,j)=>{const t=idb.transaction(STORE,'readonly'),s=t.objectStore(STORE),g=s.getAll();g.onsuccess=()=>r(g.result||[]);g.onerror=()=>j(g.error)})}
async function idbClear(){idb=idb||await openDB();return new Promise((r,j)=>{const t=idb.transaction(STORE,'readwrite');t.objectStore(STORE).clear();t.oncomplete=()=>r();t.onerror=()=>j(t.error)})}
async function idbPutMany(a){idb=idb||await openDB();return new Promise((r,j)=>{const t=idb.transaction(STORE,'readwrite'),s=t.objectStore(STORE);(a||[]).forEach(x=>s.put(x));t.oncomplete=()=>r();t.onerror=()=>j(t.error)})}
(async()=>{try{const it=await idbGetAll();if(!it||!it.length){const ls=localStorage.getItem('historia.stories');if(ls){const arr=(JSON.parse(ls)||[]).filter(Boolean).map(s=>({...s,id:s.id||Date.now()+Math.random().toString(36).slice(2)}));await idbPutMany(arr);localStorage.setItem('historia.stories',JSON.stringify(arr));}}}catch(e){}})();
const _set=localStorage.setItem.bind(localStorage);localStorage.setItem=function(k,v){_set(k,v);if(k==='historia.stories'){try{const a=JSON.parse(v||'[]');(async()=>{try{await idbClear();await idbPutMany(a||[])}catch{}})()}catch{}}};
window.addEventListener('beforeunload',()=>{try{const ls=localStorage.getItem('historia.stories');if(ls){const a=JSON.parse(ls);(async()=>{try{await idbClear();await idbPutMany(a||[])}catch{}})()}}catch{}});
function save(){localStorage.setItem('historia.stories',JSON.stringify(S.stories))}
function onReady(f){if(document.readyState!=='loading')f();else document.addEventListener('DOMContentLoaded',f)}
onReady(async()=>{S.stories=await (async()=>{try{const it=await idbGetAll();if(it&&it.length)return it;const ls=localStorage.getItem('historia.stories');return ls?JSON.parse(ls):[]}catch{const ls=localStorage.getItem('historia.stories');return ls?JSON.parse(ls):[]}})();wire();list();const terms=localStorage.getItem('hx_terms_accepted')==='1', lic=!!localStorage.getItem('hx_license_key');if(!terms)$('#terms').classList.remove('hidden');else if(!lic)$('#license').classList.remove('hidden')});
function wire(){ $('#terms_accept').onchange=()=>$('#terms_ok').disabled=!$('#terms_accept').checked; $('#terms_ok').onclick=()=>{localStorage.setItem('hx_terms_accepted','1');$('#terms').classList.add('hidden');if(!localStorage.getItem('hx_license_key'))$('#license').classList.remove('hidden')};
$('#btnTutorial').onclick=()=>$('#tutorial').classList.remove('hidden');$('#tutorial_close').onclick=()=>$('#tutorial').classList.add('hidden');
$('#btnSettings').onclick=()=>$('#license').classList.toggle('hidden');$('#lic_cancel').onclick=()=>$('#license').classList.add('hidden');$('#lic_ok').onclick=()=>{localStorage.setItem('hx_license_key',$('#licenseKey').value.trim());localStorage.setItem('hx_model_key',$('#modelKey').value.trim()||'gemini-1.5-pro');localStorage.setItem('hx_gh_owner',$('#gh_owner').value.trim());localStorage.setItem('hx_gh_repo',$('#gh_repo').value.trim());localStorage.setItem('hx_gh_branch',$('#gh_branch').value.trim());localStorage.setItem('hx_gh_token',$('#gh_token').value.trim());$('#license').classList.add('hidden')};
$('#btnCreate').onclick=()=>{$('#screenMenu').classList.add('hidden');$('#screenCreator').classList.remove('hidden');$('#btnHome').classList.remove('hidden')};
$('#btnCancel').onclick=()=>{$('#screenCreator').classList.add('hidden');$('#screenMenu').classList.remove('hidden');$('#btnHome').classList.add('hidden')};
$('#btnHome').onclick=()=>{$('#screenReader').classList.add('hidden');$('#screenCreator').classList.add('hidden');$('#screenMenu').classList.remove('hidden');$('#btnHome').classList.add('hidden');list()};
const rate=$('#rateSlider'),vol=$('#volSlider'),rateVal=$('#rateVal'),volVal=$('#volVal');$('#pillRate').onclick=()=>$('#wrapRate').classList.toggle('open');$('#pillVol').onclick=()=>$('#wrapVol').classList.toggle('open');$('#muteBtn').onclick=()=>{vol.value='0';vol.oninput()};
let utt=null;if('speechSynthesis'in window){$('#btnSpeak').onclick=()=>{const t=$('#narrativa')?.innerText?.trim();if(!t)return;window.speechSynthesis.cancel();spk(t)};$('#btnStop').onclick=()=>speechSynthesis.cancel();rate.oninput=()=>{rateVal.textContent=parseFloat(rate.value).toFixed(2)+'x';if(utt)utt.rate=parseFloat(rate.value)};vol.oninput=()=>{volVal.textContent=Math.round(parseFloat(vol.value)*100)+'%';if(utt)utt.volume=parseFloat(vol.value)};function spk(t){const u=new SpeechSynthesisUtterance(t);utt=u;u.rate=parseFloat(rate.value||'1');u.volume=parseFloat(vol.value||'0.9');speechSynthesis.speak(u);u.onend=()=>utt=null;}} 
$('#btnGenerate').onclick=()=>{const st={id:Date.now()+Math.random().toString(36).slice(2),title:$('#f_title').value.trim()||'Sem título',genre:$('#f_genre').value,nuclei:$('#f_nuclei').value.trim(),brief:$('#f_brief').value.trim(),chapters:Math.max(1,Math.min(10,parseInt($('#f_capitulos').value||'10',10))),firstPerson:$('#f_firstperson').checked,path:[],store:{}};S.stories.push(st);save();open(st.id,true)};$('#btnBack').onclick=()=>{if(S.chapterIdx>0){S.chapterIdx--;renderFromStore()}}}
function list(){const host=$('#listStories');host.innerHTML='';S.stories.forEach(st=>{const d=document.createElement('div');d.className='card';d.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-weight:700">${st.title}</div><div class="small">${st.genre} • ${st.chapters} caps • ${st.firstPerson?'1ª pessoa':'3ª pessoa'}</div></div><div style="display:flex;gap:8px"><button class="btn" data-a="o">▶️ Ler</button><button class="btn" data-a="x">🗑️</button></div></div>`;d.querySelector('[data-a=o]').onclick=()=>open(st.id);d.querySelector('[data-a=x]').onclick=()=>{if(confirm('Excluir roteiro?')){const i=S.stories.findIndex(x=>x.id===st.id);if(i>=0){S.stories.splice(i,1);save();list();}}};host.appendChild(d)})}
async function open(id,genFirst=false){const st=S.stories.find(x=>x.id===id);if(!st)return;S.current=st;S.chapterIdx=st.store.lastIdx||0;$('#screenMenu').classList.add('hidden');$('#screenCreator').classList.add('hidden');$('#screenReader').classList.remove('hidden');$('#btnHome').classList.remove('hidden');if(genFirst||!st.store['cap_'+S.chapterIdx])await genAndRender();else renderFromStore()}
function renderFromStore(){const st=S.current,i=S.chapterIdx,data=st.store['cap_'+i];if(!data)return;$('#capitulo').textContent='Capítulo '+(i+1);$('#titulo').textContent=data.title||('Capítulo '+(i+1));const host=$('#narrativa');host.innerHTML='';host.appendChild(divHTML(toHTML(data.part1||'')));choices(data.decision50,'50')}
function divHTML(h){const d=document.createElement('div');d.className='story';d.innerHTML=h;return d}function toHTML(t){return (t||'').split(/\n+/).map(p=>`<p>${p}</p>`).join('')}
async function callGemini(prompt){const key=localStorage.getItem('hx_license_key');const model=localStorage.getItem('hx_model_key')||'gemini-1.5-pro';if(!key)return fallback();const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`;const body={contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.8,topK:40,topP:0.95}};try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)return fallback();const d=await r.json();const out=(d?.candidates?.[0]?.content?.parts||[]).map(p=>p.text).join('');return out||fallback()}catch{return fallback()}}
function buildPrompt(story,i,ctx=''){const wpm=180,target=15*wpm,pov=story.firstPerson?'primeira pessoa':'terceira pessoa',death=story.firstPerson?'ATENÇÃO: fim precoce é possível se o protagonista morrer.':'';return(`Você é roteirista de novelas brasileiras. Escreva o CAPÍTULO ${i+1} em ${pov}.
Use TODOS os núcleos: ${story.nuclei}. Gênero: ${story.genre}. Evite clichês; foque em cenas, ações e DIÁLOGOS naturais.
Contexto acumulado até aqui: ${ctx||'início'}. Duração alvo ~${target} palavras, com decisões aos 50% e 90%. ${death}
FORMATO EXATO (apenas JSON válido):
{ "title": "...", "part1": "...", "decision50": ["A","B","C"], "part2": "...", "decision90": ["A","B","C"], "conclusion": "..." }
Enredo breve: ${story.brief}`).trim()}
function fallback(){const o={title:'Capítulo',part1:'[Offline] Adicione a licença em 🔐 Licença para gerar com IA.',decision50:['Assumir o risco','Buscar aliados','Investigar melhor'],part2:'Consequências diretas da escolha anterior avançam o enredo.',decision90:['Confrontar','Guardar segredo','Mudar o plano'],conclusion:'Conclusão provisória do capítulo com gancho.'};return'```json\n'+JSON.stringify(o,null,2)+'\n```'}
function parse(raw){const j=(raw.match(/```json([\s\S]*?)```/i)?.[1]||raw).trim();return JSON.parse(j)}
function ctxUntil(i,st){const a=[];for(let k=0;k<i;k++){const c=st.store['cap_'+k];if(!c)break;a.push((c.title?c.title+': ':'')+c.part1.slice(0,400));const p50=st.path.find(p=>p.cap===k&&p.at===50);if(p50)a.push('Escolha 50%: '+p50.choice);a.push(c.part2.slice(0,300));const p90=st.path.find(p=>p.cap===k&&p.at===90);if(p90)a.push('Escolha 90%: '+p90.choice);a.push(c.conclusion.slice(0,200))}return a.join('\n')}
async function genAndRender(){const st=S.current,i=S.chapterIdx,ctx=ctxUntil(i,st);$('#capitulo').textContent='Capítulo '+(i+1);$('#titulo').textContent='Gerando…';$('#narrativa').innerHTML='<p><em>Gerando capítulo com IA…</em></p>';$('#choices').innerHTML='';let raw,obj;try{raw=await callGemini(buildPrompt(st,i,ctx));obj=parse(raw)}catch(e){raw=fallback();obj=parse(raw)}st.store['cap_'+i]=obj;st.store.lastIdx=i;save();renderFromStore();if(i+1<st.chapters)preload(i+1)}
async function preload(n){const st=S.current;if(!st||st.store['cap_'+n])return;try{const ctx=ctxUntil(n,st);const raw=await callGemini(buildPrompt(st,n,ctx));const obj=parse(raw);st.store['cap_'+n]=obj;save()}catch{}}
function choices(arr,m){const host=$('#choices');host.innerHTML='';const icons=['🚪','🧭','⚠️'];(arr||[]).slice(0,3).forEach((t,i)=>{const d=document.createElement('div');d.className='choice';d.innerHTML=`<div class="ico">${icons[i%icons.length]}</div><div><div class="label">Opção ${'ABC'[i]}</div><div class="txt">${t}</div><div class="btns"><button class="btn" data-i="${i}" data-m="${m}">Escolher</button></div></div>`;d.querySelector('button').onclick=()=>choose(m,t);host.appendChild(d)});$('#btnNewOptions').onclick=()=>regen(m)}
async function regen(m){const st=S.current,i=S.chapterIdx,data=st.store['cap_'+i];if(!data)return;const shown=$('#narrativa').innerText.slice(-1200);const key=localStorage.getItem('hx_license_key');if(!key){const v=['Apostar tudo agora','Chamar reforços discretamente','Observar e recolher provas'];if(m==='50')data.decision50=v;else data.decision90=v.map(x=>x+' (ajustada)');save();choices(m==='50'?data.decision50:data.decision90,m);return}const model=localStorage.getItem('hx_model_key')||'gemini-1.5-pro';const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`;const ask=`Gere exatamente 3 opções curtas e distintas, coerentes com o trecho a seguir, que sejam divisor de caminho (marker ${m}). Responda APENAS JSON: ["A","B","C"]. Trecho:\n${shown}`;try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:ask}]}]})});const d=await r.json();const out=(d?.candidates?.[0]?.content?.parts||[]).map(p=>p.text).join('');const j=(out.match(/```json([\s\S]*?)```/i)?.[1]||out).trim();const arr=JSON.parse(j);if(Array.isArray(arr)&&arr.length>=3){if(m==='50')data.decision50=arr.slice(0,3);else data.decision90=arr.slice(0,3);save();choices(arr.slice(0,3),m)}}catch{}}
function choose(m,t){const st=S.current,i=S.chapterIdx,data=st.store['cap_'+i];st.path.push({cap:i,at:parseInt(m,10),choice:t});save();if(m==='50'){$('#narrativa').appendChild(divHTML(toHTML(data.part2||'')));choices(data.decision90,'90')}else{$('#narrativa').appendChild(divHTML(toHTML(data.conclusion||'')));if(st.firstPerson&&/morr(i|eu)|morte|fim precoce/i.test((data.conclusion||'')+(data.part2||''))){alert('Fim precoce! Este protagonista não sobreviveu.');$('#btnNext').onclick=()=>$('#btnHome').click();return}$('#btnNext').onclick=()=>{if(i+1<st.chapters){S.chapterIdx++;genAndRender()}else{alert('Temporada concluída!');$('#btnHome').click()}}}}
})();